---


BASE_OUTPUT_DIR: ./CELLECT-MAGMA-EXAMPLE


SPECIFICITY_INPUT:
  - id: mousebrain-test
    path: example/mousebrain-test.csv.gz # 2 annotations
  - id: tabula_muris-test
    path: example/tabula_muris-test.csv # 5 annotations


GWAS_SUMSTATS:
  - id: BMI_UKBB_Loh2018_no_mhc
    path: example/BMI_UKBB_Loh2018_no_mhc.sumstats
  - id: BMI_UPDATE_Yengo2018_no_mhc
    path: example/BMI_UPDATE_Yengo2018_no_mhc.sumstats


ANALYSIS_TYPE: 
  prioritization: True
  conditional: False


WINDOW_DEFINITION: 
  WINDOW_SIZE_KB:
    100


MAGMA_CONST:
  DATA_DIR: 
    data/magma
  NUMPY_CORES: 
    1
