name: munge_magma
channels:
        - defaults
        - bioconda
dependencies:
        - argparse
        - joblib
        - python=2.7
        - bitarray=0.8
        - numpy>=1.13.1
        - pandas>=0.18.1
        - scipy>=0.18
        - pip
        - pip: # following added under pip to avoid conda 'ResolvePackageNotFound' error
                - pandas==0.20.1
                - numpy==1.13.1
