---

############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################


######### GENERAL ###########

BASE_WORKING_DIR: # This is the output directory. Snakemake will make a new directory /{BASE_WORKING_DIR}/{USERNAME}/cellect-LDSC where all the output made by the pipeline is saved
  /scratch

RUN_PREFIXES: # The run prefixes is the unique part of the multigeneset file i.e. multigeneset.{RUN_PREFIX}.txt 
  - mousebrain_all.sem_mean.subset190629

CHROMOSOMES: 
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
DATASET_NAME: # The dataset LD scores must be pre-computed and in {BASE_WORKING_DIR}/pre-computation/control.all_genes_in_dataset/per_annotation
  mousebrain


########### LDSC ############

LDSC_MULTIGENESET_DIR: # All multigeneset files must be here
  /projects/alegbe/CELLECT-data/ldsc/multigenesets
LDSC_GWAS_SUMSTATS: # This is the unique name of the GWAS sumstats file i.e. {LDSC_GWAS_SUMSTAT}.sumstats.gz
  - EA3_Lee2018
  - HEIGHT_UKBB_Loh2018
LDSC_WINDOW_SIZE_KB: # This parameter specifies the size (in KB) of the window that will be created around all genes when mapping SNPs to genes
  100
LDSC_SNPSNAP_WINDOWS: # Will override LDSC_WINDOW_SIZE_KB if True and map SNPs to genes that they are in LD with using SNPsnap
  True



############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################


########### LDSC ############

# Most of this section could just point to the CELLECT-data directory and then we complete all these paths in the Snakefile

LDSC_BFILE_PATH:
  /projects/alegbe/CELLECT-data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC
LDSC_PRINT_SNPS_FILE:
  /projects/alegbe/CELLECT-data/ldsc/print_snps.txt
LDSC_SCRIPT:
  /projects/alegbe/ldsc/ldsc.py
LDSC_MOUSE_GENE_MAPPING:
  /projects/alegbe/CELLECT-data/ldsc/gene_annotation.hsapiens_mmusculus_unique_orthologs.GRCh37.ens_v91.txt.gz
LDSC_GENE_COORD_FILE:
  /projects/alegbe/CELLECT-data/ldsc/gene_annotation.hsapiens_all_genes.GRCh37.ens_v91.LDSC_fmt.txt
LDSC_BASELINE:
  /projects/alegbe/CELLECT-data/ldsc/baseline_v1.1/baseline.
LDSC_LD_SCORE_WEIGHTS:
  /projects/alegbe/CELLECT-data/ldsc/1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC.
LDSC_GWAS_DIR:
  /projects/alegbe/CELLECT-data/ldsc/gwas_sumstats_ldsc
LDSC_SNPSNAP_FILE:
  /projects/alegbe/CELLECT-data/ldsc/ld0.5_collection.tab
LDSC_NUMPY_MULTITHREADING:
  1
