---

############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################

BASE_OUTPUT_DIR: # Snakemake will make a new directory {BASE_WORKING_DIR}/{USERNAME}/cellect-LDSC where all the output made by the pipeline is saved e.g. LD scores, pvals result files, etc.
  /scratch

# Replaces RUN_PREFIXES and multigeneset_dir
SPECIFICITY_INPUT:
  - name: Mousebrain.ESmu190806 # The name give to the output files
    path: ~/CELLECT-data/ldsc/multigenesets/mousebrain.ESmu.test1.txt # The path to the file containing the multigeneset
  # - name: # if left blank can we try to use the filename without extension as name?
  #   path: ~/CELLECT-data/ldsc/multigenesets/tabula_muris.ESmu.test2.txt

# Input must be munged for LDSC
  GWAS_SUMSTATS:
  - name: EA3_Lee2018
    path: /path/to/EA3_Lees2018.sumstats.gz 
  - name: HEIGHT_UKBB_Loh2018
    path: /path/to/HEIGHT_UKBB_Loh2018.sumstats.gz

LDSC: # Options for LDSC
  WINDOW_SIZE_KB:
  100
  SNPSNAP_WINDOWS: # Will override WINDOW_SIZE_KB if True
  False
  WGCNA: # Will be deprecated
    False
  DATASET_NAME:
    "mousebrain"


############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################

CHROMOSOMES: 
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]


LDSC:
  DATA_DIR: # All the unchanging data needed to run CELLECT-LDSC is in this directory. It must be downloaded via the link in the repo.
    /project/alegbe/CELLECT-data/ldsc 
  LDSC_DIR: # This path should point to the a cloned version of the github repo pascaltimshel/ldsc
    /project/alegbe/ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1 