---

# Please use absolute paths, ~ and environment variables are not processed

############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################

BASE_OUTPUT_DIR: # Snakemake will make a new directory {BASE_WORKING_DIR}/{USERNAME}/cellect-LDSC where all the output made by the pipeline is saved e.g. LD scores, pvals result files, etc.
  /scratch

# Replaces RUN_PREFIXES and multigeneset_dir
SPECIFICITY_INPUT:
  - name: Mousebrain.ESmu190811 # The name give to the output files, MUST be unique and NO double underscores allowed
    path: /projects/alegbe/CELLECT-data/specificity_matrices/mousebrain-spec-matrix-190811.csv # The path to the matrix containing specificity scores for each genomic region, does not need to be unique
  - name: Tabula_Muris.ESmu190811
    path: /projects/alegbe/CELLECT-data/specificity_matrices/tabula_muris-spec-matrix-190811.csv

# To use sumstats with LDSC must be munged first by the munge_sumstats.py script found in the LDSC repo.
GWAS_SUMSTATS:
  - name: EA3_Lee2018
    path: /projects/alegbe/CELLECT-data/gwas/EA3_Lee2018.sumstats.gz 
  - name: HEIGHT_UKBB_Loh2018
    path: /projects/alegbe/CELLECT-data/gwas/HEIGHT_UKBB_Loh2018.sumstats.gz

LDSC_VAR: # Options for LDSC
  WINDOW_SIZE_KB:
    100
  SNPSNAP_WINDOWS: # Will override WINDOW_SIZE_KB if True and map SNPs to genes that they are in LD with using SNPsnap
    True


############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################

CHROMOSOMES: 
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]


LDSC_CONST:
  DATA_DIR: # All the unchanging data needed to run CELLECT-LDSC is in this directory. It must be downloaded via the link in the repo.
    /projects/alegbe/CELLECT-data/ldsc 
  LDSC_DIR: # This path should point to the a cloned version of the github repo pascaltimshel/ldsc
    /projects/alegbe/ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1