---

############################################################################################################################
################################################ INFORMATION ################################################################
############################################################################################################################

# All file paths accept absolute and relative paths
# Environment variables (including ~) are not processed, so don't use them in this config.


############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################

BASE_OUTPUT_DIR: /scratch/timshel/CELLECT-LDSC # for currect working directory use: ./CELLECT-LDSC
# Folder where all the output is saved (LD scores, prioritization results files, etc.) Directory will be created if it does not exists.
  

### SPECIFICITY_INPUT: list of dictionaries
# id: identifier for the dataset. Output files will be prefixed with the id. MUST be unique and NO double underscores allowed
# path: the path to the matrix containing specificity scores for each genomic region, does not need to be unique
SPECIFICITY_INPUT:
  - id: mousebrain-test
    path: example/mousebrain-test.csv.gz
  #- id: tabula_muris-test
  #  path: example/tabula_muris-test.csv

### GWAS_SUMSTATS: list of dictionaries
# id: identifier for GWAS. MUST be unique and NO double underscores allowed
# path: filepath for munged GWAS sumstats.
# OBS: sumstats MUST be munged using the munge_sumstats.py script found in the LDSC repo.
GWAS_SUMSTATS:
  - id: EA3_Lee2018
    path: example/EA3_Lee2018.sumstats.gz 
  - id: BMI_Yengo2018
    path: example/BMI_Yengo2018.sumstats.gz


ANALYSIS_MODE: # specify what analysis modes to run. At least one mode needs to be specified.
  prioritization: True # prioritizes all cell-type annotations in the SPECIFICITY_INPUT datasets
  conditional: True # performs conditional analysis for selected annotations.
  heritability: False # estimates heritability for selected annotations.


LDSC_VAR: # Options for LDSC
  WINDOW_SIZE_KB:
    100
  WINDOW_LD_BASED: # Will override WINDOW_SIZE_KB if True. If True, use LD-based 'window' to map SNPs to genes. 
    False


############################################################################################################################
############################################## conditional analysis ########################################################
############################################################################################################################

### CONDITIONAL_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to condition on
# NOTE: you can delete or leave these dicts blank if 'mode' is not activated
CONDITIONAL_INPUT:
  - id: mousebrain-test
    annotations: ['ABC', 'ACBG']
  # - id: tabula_muris-test
  #   annotations: ['XX']


############################################################################################################################
############################################## heritability analysis ########################################################
############################################################################################################################

### HERITABILITY_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to estimate heritability for
# NOTE: you can delete or leave these dicts blank if 'mode' is not activated
HERITABILITY_INPUT:
  - id: mousebrain-test
    annotations: ['TEGLU23', 'DEINH3', 'MEGLU1', 'MEINH2', 'DEGLU5', 'MEGLU10', 'TEGLU17', 'MEGLU11', 'TEGLU4', 'DEGLU4', 'TEINH12']
  - id: tabula_muris-test
    annotations: ['Spleen.T_cell', 'Thymus.immature_T_cell', 'Fat.T_cell', 'Spleen.B_cell']


############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################

# You generally do not need to change these variables.

LDSC_CONST:
  DATA_DIR: # Path to the data used for CELLECT-LDSC (baseline model, gene mapping etc).
    data/ldsc
  LDSC_DIR: # Path to the a cloned version of the github repo pascaltimshel/ldsc. This is included as a git submodule.
    ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1
