---

############################################################################################################################
################################################ INFORMATION ################################################################
############################################################################################################################

# All file paths accept absolute and relative paths
# Environment variables (including ~) are not processed, so don't use them in this config.


############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################

BASE_OUTPUT_DIR: ./CELLECT-MAGMA-EXAMPLE 
# Folder where all the output is saved (ZSTAT files, prioritization results files, etc.) Directory will be created if it does not exists.
  

### SPECIFICITY_INPUT: list of dictionaries
# id: identifier for the dataset. Output files will be prefixed with the id. MUST be unique and NO double underscores allowed
# path: the path to the matrix containing specificity scores for each genomic region, does not need to be unique
SPECIFICITY_INPUT:
  - id: mousebrain-test
    path: example/mousebrain-test.csv.gz # 2 annotations
  # - id: tabula_muris-test
  #   path: example/tabula_muris-test.csv # 5 annotations


### GWAS_SUMSTATS: list of dictionaries
# id: identifier for GWAS. MUST be unique and NO double underscores allowed
# path: filepath for munged GWAS sumstats.
# OBS: sumstats MUST be munged using the mtag_munge.py script found in the repo and then unpacked via 'gunzip' command. 
# MAGMA takes as input unarchived / simple text files only.
GWAS_SUMSTATS:
  - id: BMI_UKBB_Loh2018_no_mhc
    path: example/BMI_UKBB_Loh2018_no_mhc.sumstats 
  - id: BMI_UPDATE_Yengo2018_no_mhc
    path: example/BMI_UPDATE_Yengo2018_no_mhc.sumstats


ANALYSIS_TYPE: # specify what analysis modes to run. At least one mode needs to be specified.
  prioritization: True # prioritizes all cell-type annotations in the SPECIFICITY_INPUT datasets
  conditional: False # performs conditional analysis for selected annotations.


WINDOW_DEFINITION: # Window definition for mapping gene specificity values to SNPs
  WINDOW_SIZE_KB:
    100


############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################

# You generally do not need to change these variables.

MAGMA_CONST:
  DATA_DIR:    # Path to the data used for CELLECT-MAGMA (baseline model, gene mapping etc).
    data/magma
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via the '-j' flag.
    1
